import express from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.post('/api/book', async (req, res) => {
    const { name, email, phone, industry, truckCount, score, date, time } = req.body;

    console.log('--- NEW LEAD GENERATED ---');
    console.log(`Company: ${name}`);
    console.log(`Email: ${email}`);
    console.log(`Phone: ${phone}`);
    console.log(`Industry: ${industry}`);
    console.log(`Trucks: ${truckCount}`);
    console.log(`Diagnostic Score: ${score}/100`);
    console.log(`Requested Time: March ${date}, 2026 at ${time}`);
    console.log('---------------------------');

    // Integrate Resend to send real emails
    if (process.env.RESEND_API_KEY) {
      try {
        const { Resend } = await import('resend');
        const resend = new Resend(process.env.RESEND_API_KEY);
        
        await resend.emails.send({
          from: 'Integr-AI-tion <onboarding@resend.dev>',
          to: 'thehomeaseaiteam@gmail.com',
          subject: `New Lead: ${name} (${industry})`,
          html: `
            <div style="font-family: sans-serif; color: #333;">
              <h1 style="color: #00E5FF;">New Diagnostic Lead</h1>
              <p>A new strategy session has been requested via the Integr-AI-tion platform.</p>
              <hr />
              <p><strong>Name:</strong> ${name}</p>
              <p><strong>Email:</strong> ${email}</p>
              <p><strong>Phone:</strong> ${phone}</p>
              <p><strong>Industry:</strong> ${industry}</p>
              <p><strong>Trucks:</strong> ${truckCount}</p>
              <p><strong>Diagnostic Score:</strong> ${score}/100</p>
              <p><strong>Scheduled Time:</strong> March ${date}, 2026 at ${time}</p>
              <hr />
              <p style="font-size: 12px; color: #666;">This lead was generated by the Integr-AI-tion Diagnostic Engine.</p>
            </div>
          `
        });
        console.log('Email sent successfully via Resend');
      } catch (error) {
        console.error('Failed to send email via Resend:', error);
      }
    } else {
      console.warn('RESEND_API_KEY not found in environment variables. Email not sent.');
    }

    res.json({ success: true, message: 'Lead captured successfully' });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (req, res) => {
      res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
